language: node_js
node_js:
  - "11.11.0"

npm:
  - "6.9.0"

install:
  - npm install

script:
  - npm run test

deploy:
  provider: script
  script:
  - npm run build
  - ./node_modules/.bin/now secrets add SERVER_PORT $SERVER_PORT
  - ./node_modules/.bin/now secrets add JWT_SECRET $JWT_SECRET
  - ./node_modules/.bin/now secrets add DB_HOST $DB_HOST
  - ./node_modules/.bin/now secrets add DB_PORT $DB_PORT
  - ./node_modules/.bin/now secrets add DB_USER $DB_USER
  - ./node_modules/.bin/now secrets add DB_PASSWORD $DB_PASSWORD
  - ./node_modules/.bin/now secrets add DB_NAME $DB_NAME
  - ./node_modules/.bin/now --token=$NOW_TOKEN
  skip_cleanup: true
  on:
    branch: master
    