language: node_js
node_js:
  - "11.11.0"

npm:
  - "6.9.0"

install:
  - npm install

script:
  - npm run test

deploy:
  provider: script
  script: 
    - npm run build
    - npm run deploy
  skip_cleanup: true
  on:
    branch: master
    