language: node_js
node_js:
  - "10.15.3"

services:
  - docker

before_install:
  - docker pull mysql:latest
  - docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
  - ls

install:
  - npm install

script:
  - npm run test