language: node_js
node_js:
  - "11.11.0"

npm:
  - "6.9.0"

services:
  - docker

before_install:
  - docker pull mysql:latest
  - docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
  - echo '#DB credentials \n DB_TYPE="mysql" \n DB_HOST="localhost" \n DB_PORT=3306 \n DB_USER="root" \n DB_PASSWORD="root" \n DB_NAME="hallo" \n SERVER_PORT=1337' > .env

install:
  - npm install

script:
  - npm run test