apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{beta}}backend
  namespace: salvemundi
spec:
  selector:
    matchLabels:
      app: {{beta}}salvemundi-backend
      tier: backend
  replicas: 1
  template:
    metadata:
      name: {{beta}}salvemundi-backend
      namespace: salvemundi
      labels:
        app: {{beta}}salvemundi-backend
        tier: backend
    spec:
      containers:
      - name: {{beta}}salvemundi-backend
        image: svsalvemundi/backend:{{samu_backend_version}}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: DB_HOST
          value: "{{db_host}}"
        - name: DB_PORT
          value: "{{db_port}}"
        - name: DB_USER
          value: "{{db_user}}"
        - name: DB_PASSWORD
          value: "{{db_password}}"
        - name: DB_NAME
          value: "{{db_name}}"
        - name: SERVER_PORT
          value: "1337"
        - name: JWT_SECRET
          value: "{{jwt_secret}}"
        - name: MOLLIE_API_KEY
          value: "{{mollie_key}}"
        - name: REDIRECT_URL
          value: "https://{{beta_site_link}}salvemundi.nl/home/"
        - name: MOLLIE_WEBHOOK_URL
          value: "https://{{beta_link}}api.salvemundi.nl/webhook/"
        - name: SENDGRID_PASS
          value: "{{sendgrid_password}}"
        - name: SENDGRID_USER
          value: "{{sendgrid_user}}"
        ports:
        - containerPort: 1337

---

apiVersion: v1
kind: Service
metadata:
  name: {{beta}}backend-service
  namespace: salvemundi
spec:
  type: NodePort
  selector:
    app: {{beta}}salvemundi-backend
    tier: backend
  ports:
    - port: 1337

